# THE CABOOSE IS AN ABSOLUTE WAGON
name: MRI 2.3 X Hashie WAGON (EOL)

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
      - '*-stable'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Specs ${{ matrix.ruby }} ${{ matrix.appraisal }}${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby 2.3
          - ruby: "ruby-2.3"
            appraisal: "ruby-2-3-hashie_v0"
            exec_cmd: "rake test"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          # Ruby 2.3
          - ruby: "ruby-2.3"
            appraisal: "ruby-2-3-hashie_v1"
            exec_cmd: "rake test"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          # Ruby 2.3
          - ruby: "ruby-2.3"
            appraisal: "ruby-2-3-hashie_v2"
            exec_cmd: "rake test"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          # Ruby 2.3
          - ruby: "ruby-2.3"
            appraisal: "ruby-2-3-hashie_v3"
            exec_cmd: "rake test"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          # Ruby 2.3
          - ruby: "ruby-2.3"
            appraisal: "ruby-2-3-hashie_v4"
            exec_cmd: "rake test"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          # Ruby 2.3
          - ruby: "ruby-2.3"
            appraisal: "ruby-2-3-hashie_v5"
            exec_cmd: "rake test"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: false

      # Raw `bundle` will use the BUNDLE_GEMFILE set to matrix.gemfile (i.e. Appraisal.root)
      # We need to do this first to get appraisal installed.
      # NOTE: This does not use the primary Gemfile at all.
      - name: Install Root Appraisal
        run: bundle > /dev/null 2>&1
      - name: Appraisal for ${{ matrix.appraisal }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle > /dev/null 2>&1
      - name: Tests for ${{ matrix.ruby }} via ${{ matrix.exec_cmd }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec ${{ matrix.exec_cmd }}
